"""
machine_state_writer.py

Write timestamped MAD-X-readable machine-state override/log files.
"""

import json
import os
from datetime import datetime


def _safe_time_string(cycle_time_ms):
    """
    Convert cycle time into a filename-safe string.
    """

    return f"{float(cycle_time_ms):.6f}".replace(".", "p").replace("-", "m")


def make_machine_state_filename(machine_state, output_dir="./machine_states"):
    """
    Make a timestamped machine-state filename.
    """

    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
    time_string = _safe_time_string(machine_state.cycle_time_ms)

    filename = f"machine_state_{timestamp}_t{time_string}ms.strength"

    return os.path.join(output_dir, filename)


def format_madx_value(value):
    """
    Format a Python value as a MAD-X-readable value.
    """

    if value is None:
        return "0.0"

    if isinstance(value, bool):
        return "true" if value else "false"

    if isinstance(value, int):
        return str(value)

    if isinstance(value, float):
        return f"{value:.16g}"

    return str(value)


def write_assignment(file_handle, name, value, assignment=":="):
    """
    Write a MAD-X assignment.
    """

    file_handle.write(f"{name} {assignment} {format_madx_value(value)};\n")


def write_comment(file_handle, text=""):
    """
    Write a MAD-X comment line.
    """

    if text == "":
        file_handle.write("!\n")
    else:
        file_handle.write(f"! {text}\n")


def write_comment_block(file_handle, machine_state):
    """
    Write human-readable metadata to the top of the machine-state file.
    """

    beam = machine_state.beam_summary_dict()

    write_comment(file_handle, "ISIS RCS machine-state override file")
    write_comment(file_handle, "Generated by machine_state_writer.py")
    write_comment(file_handle, f"timestamp = {machine_state.timestamp}")
    write_comment(file_handle, f"cycle_time_ms = {machine_state.cycle_time_ms}")
    write_comment(file_handle, f"main_magnet_mode = {machine_state.main_magnet_mode}")
    write_comment(file_handle, f"tune_method = {machine_state.tune_method}")
    write_comment(file_handle, f"requested_qx = {machine_state.requested_qx}")
    write_comment(file_handle, f"requested_qy = {machine_state.requested_qy}")
    write_comment(file_handle, f"base_qx = {machine_state.base_qx}")
    write_comment(file_handle, f"base_qy = {machine_state.base_qy}")
    write_comment(file_handle, f"error_table_path = {machine_state.error_table_path}")
    write_comment(file_handle, "")

    write_comment(file_handle, "Beam state")
    for key, value in beam.items():
        write_comment(file_handle, f"{key} = {value}")

    write_comment(file_handle, "")


def write_machine_state_file(
    machine_state,
    output_dir="./machine_states",
    filename=None,
    write_json_sidecar=True,
):
    """
    Write a complete timestamped MAD-X-readable machine-state file.

    The resulting file is both:
        - a MAD-X override file
        - a human-readable machine-state log
    """

    os.makedirs(output_dir, exist_ok=True)

    if filename is None:
        path = make_machine_state_filename(
            machine_state=machine_state,
            output_dir=output_dir,
        )
    else:
        path = os.path.join(output_dir, filename)

    beam = machine_state.beam_summary_dict()

    with open(path, "w") as f:
        write_comment_block(f, machine_state)

        write_comment(f, "Beam override")
        write_assignment(f, "brho", beam["brho_Tm"])
        f.write(
            "beam, particle=proton, "
            f"pc={format_madx_value(beam['momentum_GeV_c'])};\n"
        )
        write_comment(f, "")

        write_comment(f, "Main magnet scaling")
        for name, value in machine_state.main_magnet_scaling.items():
            write_assignment(f, name, value)
        write_comment(f, "")

        write_comment(f, "Tune trim quadrupole settings")
        write_assignment(f, "kqtd", machine_state.kqtd)
        write_assignment(f, "kqtf", machine_state.kqtf)
        write_comment(f, f"iqtd_A = {machine_state.iqtd_A}")
        write_comment(f, f"iqtf_A = {machine_state.iqtf_A}")
        write_comment(f, "")

        write_comment(f, "Harmonic tune settings")
        for name, value in machine_state.harmonic_tunes.items():
            write_assignment(f, name, value, assignment="=")
        write_comment(f, "")

        write_comment(f, "HD corrector kicks written to MAD-X")
        for name, value in machine_state.hd_corrector_kicks_rad.items():
            write_assignment(f, name, value)
        write_comment(f, "")

        write_comment(f, "VD corrector kicks written to MAD-X")
        for name, value in machine_state.vd_corrector_kicks_rad.items():
            write_assignment(f, name, value)
        write_comment(f, "")

        write_comment(f, "HD corrector currents retained for GUI/logging")
        for name, value in machine_state.hd_corrector_currents_A.items():
            write_comment(f, f"{name}_current_A = {value}")
        write_comment(f, "")

        write_comment(f, "VD corrector currents retained for GUI/logging")
        for name, value in machine_state.vd_corrector_currents_A.items():
            write_comment(f, f"{name}_current_A = {value}")
        write_comment(f, "")

        write_comment(f, "Machine-state JSON summary")
        summary_json = json.dumps(machine_state.summary_dict(), indent=2)
        for line in summary_json.splitlines():
            write_comment(f, line)

    if write_json_sidecar:
        json_path = os.path.splitext(path)[0] + ".json"

        with open(json_path, "w") as f:
            json.dump(machine_state.summary_dict(), f, indent=2)

    return path
